package kubeletconfig

import (
	"encoding/json"
	"fmt"

	ign3types "github.com/coreos/ignition/v2/config/v3_2/types"
	"github.com/imdario/mergo"
	configv1 "github.com/openshift/api/config/v1"
	mcfgv1 "github.com/openshift/machine-config-operator/pkg/apis/machineconfiguration.openshift.io/v1"
	ctrlcommon "github.com/openshift/machine-config-operator/pkg/controller/common"
	mtmpl "github.com/openshift/machine-config-operator/pkg/controller/template"
	"github.com/openshift/machine-config-operator/pkg/version"
	"github.com/vincent-petithory/dataurl"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	kubeletconfigv1beta1 "k8s.io/kubelet/config/v1beta1"
)

// RunKubeletBootstrap generates MachineConfig objects for mcpPools that would have been generated by syncKubeletConfig
// nolint:gocyclo
func RunKubeletBootstrap(templateDir string, kubeletConfig *mcfgv1.KubeletConfig, features *configv1.FeatureGate, controllerConfig *mcfgv1.ControllerConfig, mcpPools []*mcfgv1.MachineConfigPool) ([]*mcfgv1.MachineConfig, error) {
	var (
		kubeletIgnition            *ign3types.File
		logLevelIgnition           *ign3types.File
		autoSizingReservedIgnition *ign3types.File
	)
	userDefinedSystemReserved := make(map[string]string)

	// Validate the KubeletConfig CR if exists
	if err := validateUserKubeletConfig(kubeletConfig); err != nil {
		return nil, newForgetError(err)
	}

	featureGates, err := generateFeatureMap(features, openshiftOnlyFeatureGates...)
	if err != nil {
		return nil, err
	}

	var res []*mcfgv1.MachineConfig
	for _, pool := range mcpPools {
		role := pool.Name
		managedKey, err := getManagedKeyKubelet(pool, nil)
		if err != nil {
			return nil, err
		}

		// Generate the bootstrap KubeletConfig
		originalKubeletIgn, err := generateBootstrapKubeletConfigs(controllerConfig, templateDir, role)
		if err != nil {
			return nil, err
		}

		if originalKubeletIgn.Contents.Source == nil {
			return nil, err
		}
		dataURL, err := dataurl.DecodeString(*originalKubeletIgn.Contents.Source)
		if err != nil {
			return nil, err
		}
		originalKubeConfig, err := decodeKubeletConfig(dataURL.Data)
		if err != nil {
			return nil, err
		}

		if kubeletConfig != nil {
			// Inject TLS Options from Spec
			observedMinTLSVersion, observedCipherSuites := getSecurityProfileCiphers(kubeletConfig.Spec.TLSSecurityProfile)
			originalKubeConfig.TLSMinVersion = observedMinTLSVersion
			originalKubeConfig.TLSCipherSuites = observedCipherSuites
		}

		if kubeletConfig != nil && kubeletConfig.Spec.KubeletConfig != nil && kubeletConfig.Spec.KubeletConfig.Raw != nil {
			specKubeletConfig, err := decodeKubeletConfig(kubeletConfig.Spec.KubeletConfig.Raw)
			if err != nil {
				return nil, err
			}

			if val, ok := specKubeletConfig.SystemReserved["memory"]; ok {
				userDefinedSystemReserved["memory"] = val
				delete(specKubeletConfig.SystemReserved, "memory")
			}

			if val, ok := specKubeletConfig.SystemReserved["cpu"]; ok {
				userDefinedSystemReserved["cpu"] = val
				delete(specKubeletConfig.SystemReserved, "cpu")
			}

			// Merge the Old and New
			err = mergo.Merge(originalKubeConfig, specKubeletConfig, mergo.WithOverride)
			if err != nil {
				return nil, err
			}
			// Merge in Feature Gates
			err = mergo.Merge(&originalKubeConfig.FeatureGates, featureGates, mergo.WithOverride)
			if err != nil {
				return nil, err
			}
			// Encode the new config into raw JSON
			cfgJSON, err := EncodeKubeletConfig(originalKubeConfig, kubeletconfigv1beta1.SchemeGroupVersion)
			if err != nil {
				return nil, err
			}
			kubeletIgnition = createNewKubeletIgnition(cfgJSON)
		} else {
			// Encode the new config into raw JSON
			cfgJSON, err := EncodeKubeletConfig(originalKubeConfig, kubeletconfigv1beta1.SchemeGroupVersion)
			if err != nil {
				return nil, err
			}
			kubeletIgnition = createNewKubeletIgnition(cfgJSON)
		}

		mc, err := ctrlcommon.MachineConfigFromIgnConfig(role, managedKey, kubeletIgnition)
		if err != nil {
			return nil, err
		}

		if kubeletConfig != nil && kubeletConfig.Spec.LogLevel != nil {
			logLevelIgnition = createNewKubeletLogLevelIgnition(*kubeletConfig.Spec.LogLevel)
		}

		if kubeletConfig != nil && kubeletConfig.Spec.AutoSizingReserved != nil && len(userDefinedSystemReserved) == 0 {
			autoSizingReservedIgnition = createNewKubeletDynamicSystemReservedIgnition(kubeletConfig.Spec.AutoSizingReserved, userDefinedSystemReserved)
		}

		if len(userDefinedSystemReserved) > 0 {
			autoSizingReservedIgnition = createNewKubeletDynamicSystemReservedIgnition(nil, userDefinedSystemReserved)
		}

		tempIgnConfig := ctrlcommon.NewIgnConfig()
		if autoSizingReservedIgnition != nil {
			tempIgnConfig.Storage.Files = append(tempIgnConfig.Storage.Files, *autoSizingReservedIgnition)
		}
		if logLevelIgnition != nil {
			tempIgnConfig.Storage.Files = append(tempIgnConfig.Storage.Files, *logLevelIgnition)
		}
		if kubeletIgnition != nil {
			tempIgnConfig.Storage.Files = append(tempIgnConfig.Storage.Files, *kubeletIgnition)
		}

		rawIgn, err := json.Marshal(tempIgnConfig)
		if err != nil {
			return nil, err
		}
		mc.Spec.Config.Raw = rawIgn

		mc.SetAnnotations(map[string]string{
			ctrlcommon.GeneratedByControllerVersionAnnotationKey: version.Hash,
		})
		oref := metav1.OwnerReference{
			APIVersion: controllerKind.GroupVersion().String(),
			Kind:       controllerKind.Kind,
		}
		mc.SetOwnerReferences([]metav1.OwnerReference{oref})
		res = append(res, mc)
	}
	return res, nil
}

// generateBootstrapKubeletConfigs returns rendered default kubelet configs for bootstrap mode
func generateBootstrapKubeletConfigs(cc *mcfgv1.ControllerConfig, templatesDir, role string) (*ign3types.File, error) {
	// Render the default templates
	rc := &mtmpl.RenderConfig{ControllerConfigSpec: &cc.Spec}
	generatedConfigs, err := mtmpl.GenerateMachineConfigsForRole(rc, role, templatesDir)
	if err != nil {
		return nil, fmt.Errorf("GenerateMachineConfigsforRole failed with error %s", err)
	}
	// Find generated kubelet.config
	for _, gmc := range generatedConfigs {
		gmcKubeletConfig, err := findKubeletConfig(gmc)
		if err != nil {
			continue
		}
		return gmcKubeletConfig, nil
	}
	return nil, fmt.Errorf("could not generate old kubelet config")
}
