package kubeletconfig

import (
	"encoding/json"
	"fmt"
	"strconv"
	"strings"

	configv1 "github.com/openshift/api/config/v1"
	mcfgv1 "github.com/openshift/machine-config-operator/pkg/apis/machineconfiguration.openshift.io/v1"
	ctrlcommon "github.com/openshift/machine-config-operator/pkg/controller/common"
	"github.com/openshift/machine-config-operator/pkg/version"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

const (
	kubeletCfgMasterLabel = "pools.operator.machineconfiguration.openshift.io/master"
	kubeletCfgWorkerLabel = "pools.operator.machineconfiguration.openshift.io/worker"
)

// RunKubeletBootstrap generates MachineConfig objects for mcpPools that would have been generated by syncKubeletConfig
func RunKubeletBootstrap(templateDir string, kubeletConfigs []*mcfgv1.KubeletConfig, controllerConfig *mcfgv1.ControllerConfig, features *configv1.FeatureGate, mcpPools []*mcfgv1.MachineConfigPool) ([]*mcfgv1.MachineConfig, error) {
	generatedManagedKeys := make(map[string]string)
	generatedMCs := make(map[string]*mcfgv1.MachineConfig)
	// Validate the KubeletConfig CR if exists
	for _, kubeletConfig := range kubeletConfigs {
		if kubeletConfig == nil {
			continue
		}
		if err := validateUserKubeletConfig(kubeletConfig); err != nil {
			return nil, newForgetError(err)
		}
	}

	userDefinedSystemReserved := make(map[string]string)
	var res []*mcfgv1.MachineConfig
	for _, kubeletConfig := range kubeletConfigs {
		if kubeletConfig == nil || kubeletConfig.Spec == (mcfgv1.KubeletConfigSpec{}) {
			continue
		}
		for _, pool := range mcpPools {
			// skip the pool if no default label for kubeletconfig
			_, hasMasterLabel := pool.Labels[kubeletCfgMasterLabel]
			_, hasWorkerLabel := pool.Labels[kubeletCfgWorkerLabel]
			if !hasMasterLabel && !hasWorkerLabel {
				continue
			}
			role := pool.Name

			originalKubeConfig, err := generateOriginalKubeletConfigWithFeatureGates(controllerConfig, templateDir, role, features)
			if err != nil {
				return nil, err
			}
			if kubeletConfig.Spec.TLSSecurityProfile != nil {
				// Inject TLS Options from Spec
				observedMinTLSVersion, observedCipherSuites := getSecurityProfileCiphers(kubeletConfig.Spec.TLSSecurityProfile)
				originalKubeConfig.TLSMinVersion = observedMinTLSVersion
				originalKubeConfig.TLSCipherSuites = observedCipherSuites
			}

			kubeletIgnition, logLevelIgnition, autoSizingReservedIgnition, err := generateKubeletIgnFiles(kubeletConfig, originalKubeConfig, userDefinedSystemReserved)
			if err != nil {
				return nil, err
			}

			tempIgnConfig := ctrlcommon.NewIgnConfig()
			if autoSizingReservedIgnition != nil {
				tempIgnConfig.Storage.Files = append(tempIgnConfig.Storage.Files, *autoSizingReservedIgnition)
			}
			if logLevelIgnition != nil {
				tempIgnConfig.Storage.Files = append(tempIgnConfig.Storage.Files, *logLevelIgnition)
			}
			if kubeletIgnition != nil {
				tempIgnConfig.Storage.Files = append(tempIgnConfig.Storage.Files, *kubeletIgnition)
			}

			rawIgn, err := json.Marshal(tempIgnConfig)
			if err != nil {
				return nil, err
			}
			managedKey, err := generateSuffixManagedKeyKubelet(pool, kubeletConfig, generatedManagedKeys)
			if err != nil {
				return nil, err
			}
			var (
				mc *mcfgv1.MachineConfig
				ok bool
			)
			mc, ok = generatedMCs[managedKey]
			if !ok {
				mc, err = ctrlcommon.MachineConfigFromIgnConfig(role, managedKey, kubeletIgnition)
				if err != nil {
					return nil, err
				}
				generatedMCs[managedKey] = mc
			}

			mc.Spec.Config.Raw = rawIgn
			mc.SetAnnotations(map[string]string{
				ctrlcommon.GeneratedByControllerVersionAnnotationKey: version.Hash,
			})
			oref := metav1.OwnerReference{
				APIVersion: controllerKind.GroupVersion().String(),
				Kind:       controllerKind.Kind,
			}
			mc.SetOwnerReferences([]metav1.OwnerReference{oref})
			res = append(res, mc)
		}
	}
	return res, nil
}

// generateSuffixManagedKeyKubelet generates the number suffixed machine config name for a CR during bootstrap
func generateSuffixManagedKeyKubelet(pool *mcfgv1.MachineConfigPool, cfg *mcfgv1.KubeletConfig, managedKeys map[string]string) (string, error) {
	if len(managedKeys) == 0 {
		managedKey, err := ctrlcommon.GetManagedKey(pool, nil, "99", "kubelet", getManagedKubeletConfigKeyDeprecated(pool))
		if err != nil {
			return "", err
		}
		if cfg.Name != "" {
			managedKeys[cfg.Name] = managedKey
		} else {
			managedKeys[managedKey] = managedKey
		}
		return managedKey, nil
	}
	if cfg.Name != "" {
		managedKey, ok := managedKeys[cfg.Name]
		if ok {
			return managedKey, nil
		}
	}
	// generate new managedKey if the kubelet config name is empty or it is a new kubelet config
	maxSuffixNum := 0
	for _, v := range managedKeys {
		// string v looks like:
		// 99-worker-generated-kubelet or 99-worker-generated-kubelet-1
		tokens := strings.Split(v, "-")
		if len(tokens) == 0 {
			return "", fmt.Errorf("wrong syntax of managedKey: %v", v)
		}
		// machine config name: 99-worker-generated-kubelet has no number suffix
		if tokens[len(tokens)-1] == "kubelet" {
			continue
		}
		num, err := strconv.Atoi(tokens[len(tokens)-1])
		if err != nil {
			return "", fmt.Errorf("error parsing suffix of managedKey %v", v)
		}
		if num > maxSuffixNum {
			maxSuffixNum = num
		}
	}
	nextSuffixNum := maxSuffixNum + 1
	if nextSuffixNum > 9 {
		return "", fmt.Errorf("max number of supported kubelet config (10) has been reached. Please delete old kubelet configs before retrying")
	}
	managedKey := fmt.Sprintf("99-%s-generated-kubelet-%s", pool.Name, strconv.Itoa(nextSuffixNum))
	if cfg.Name != "" {
		managedKeys[cfg.Name] = managedKey
	} else {
		managedKeys[managedKey] = managedKey
	}
	return managedKey, nil
}
